id: P000278
initial_creation_type: ocr
created_at: 20/02/2020
last_modified_at: 2021-12-16 15:31:41.188480
source_metadata:
  id: bdr:W1KG12111
  title: སྲས་ངག་དབང་བཀྲ་ཤིས་ཀྱིས་མཛད་པའི་བསྡུས་གྲྭ། ༼བཀྲ་ཤིས་འཁྱིལ་པར་མ།༽
  author: ''
  volumes:
    d254709344ec45dbadc963949f9426a1:
      image_group_id: I1KG12142
      title: Volume 1 of sras ngag dbang bkra shis kyis mdzad pa'i bsdus grwa/ (bkra
        shis 'khyil par ma/)
      volume_number: 1
      total_pages: 316
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
